sudo: required
services:
  - docker
  
before_install:
  - docker build -t resdenia/docker-react -f Dockerfile.dev . 

script:
  - docker run resdenia/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-365780514238"
  bucket_path: "docker"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY